---
title: "Week 6: Exponential smoothing"
---

```{r}
week <- 6
source(here::here("course_info.R"))
```

## What you will learn this week

* Exponential smoothing methods with trend and seasonality
* ETS models
* Automatic model selection using the AICc

## Exercises (on your own or in tutorial)

Complete Exercises 1-4, 16, 17 from [Section 8.8](https://otexts.com/fpp3/expsmooth-exercises.html).

## Exercise solutions

<!-- ::: {.callout appearance="minimal"} -->
<!-- <i class="bi bi-download"></i> [Week 6 Tutorial Solution.html](Week6.html){download="Week 6 Tutorial Solution.html"} -->
<!-- ::: -->

## Pre-seminar activities

Read [Sections 8.4-8.7 of the textbook](https://otexts.com/fpp3/expsmooth.html) and watch all embedded videos.

<!-- ```{r} -->
<!-- #| output: asis -->
<!-- show_slides(week) -->
<!-- ``` -->

<!-- ## Seminar activities -->

<!-- ```{r} -->
<!-- #| child: activities.md -->
<!-- ``` -->


<!-- ## Seminar code -->

<!-- ::: {.callout appearance="minimal"} -->
<!-- <i class="bi bi-download"></i> [Seminar_code_week6.R](Seminar_code_week6.R){download="Seminar_code_week6.R"} -->
<!-- ::: -->



```{r, echo=FALSE}
#| output: asis
show_assignments(week)
```
