---
title: "Activities: Week 1"
editor: source
engine: knitr
filters:
  - live
  - quiz-teachr
ojs-engine: true
webr:
  packages:
    - qlcheckr
    - fpp3
    - urca
  autoload-packages: false
  repos:
    - https://repo.r-wasm.org/
    - https://learnr-academy.github.io/qlcheckr
---

{{< include /_extensions/r-wasm/live/_knitr.qmd >}}

<<<<<<< Updated upstream
# Time series data 

## Tourism Example
=======
# Time series data


## Tourism example
>>>>>>> Stashed changes

The `tourism` dataset contains the quarterly overnight trips from 1998 Q1 to 2016 Q4 across Australia.

It is disaggregated by 3 key variables:

* `State`: States and territories of Australia
* `Region`: The tourism regions are formed through the aggregation of Statistical Local Areas (SLAs) which are defined by the various State and Territory tourism authorities according to their research and marketing needs
* `Purpose`: Stopover purpose of visit: "Holiday", "Visiting friends and relatives", "Business", "Other reason".

The tsibble is shown below:

```{r}
library(fpp3)
tourism
```

Calculate the total quarterly tourists visiting Victoria from the `tourism` dataset.

```{webr}
#| exercise: filter_summarise_tourism
tourism |>
  filter(______) |>
  summarise(______)
```

```{webr}
#| exercise: filter_summarise_tourism
#| check: true
library(qlcheckr)
apply_checks(
  c(
    "You need to load the fpp3 package!" = !("fpp3" %in% .packages()),
    "You need to use the filter() function to extract only Victorian tourists." = !search_ast(ql_ast(), .fn = filter),
    "You need to use the summarise() function to sum over the Region and Purpose keys." = !search_ast(ql_ast(), .fn = summarise)
  )
)
```

::: { .hint exercise="filter_summarise_tourism"}
::: { .callout-note collapse="false"}
## Hint

To start off, filter the `tourism` dataset for only Victoria.

```r
tourism |>
  filter(State == "Victoria")
```
:::
:::

::: { .hint exercise="filter_summarise_tourism"}
::: { .callout-note collapse="false"}
## Hint

After filtering, summarise the total trips for Victoria.

```r
tourism |>
  filter(State == "Victoria") |>
  summarise(Trips = sum(Trips))
```
:::
:::

Find what combination of `Region` and `Purpose` had the maximum number of overnight trips on average.

```{webr}
#| exercise: group_summarise_filter_tourism
tourism |>
  as_tibble() |>
  group_by(______) |>
  summarise(______) |>
  filter(______)
```

```{webr}
#| exercise: group_summarise_filter_tourism
#| check: true
library(qlcheckr)
apply_checks(
  c(
    "You need to load the fpp3 package!" = !("fpp3" %in% .packages()),
    "You need to use the as_tibble() function to convert back to a tibble object." = !search_ast(ql_ast(), .fn = as_tibble),
    "You need to use the group_by() function to group by Region and Purpose." = !search_ast(ql_ast(), .fn = group_by)
  )
)
```

::: { .hint exercise="group_summarise_filter_tourism"}
::: { .callout-note collapse="false"}
## Hint

Start by using `as_tibble()` to convert `tourism` back to a tibble and group it by Region and Purpose.

```r
tourism |>
  as_tibble() |>
  group_by(Region, Purpose)
```
:::
:::

::: { .hint exercise="group_summarise_filter_tourism"}
::: { .callout-note collapse="false"}
## Hint

After grouping, summarise the mean number of trips and filter for maximum trips.

```r
tourism |>
  as_tibble() |>
  group_by(Region, Purpose) |>
  summarise(Trips = mean(Trips), .groups = "drop") |>
  filter(Trips == max(Trips))
```
:::
:::

Create a new tsibble which combines the Purposes and Regions, and just has total trips by State.

```{webr}
#| exercise: summarise_tourism_by_state
tourism |>
  group_by(______) |>
  summarise(______)
```

```{webr}
#| exercise: summarise_tourism_by_state
#| check: true
library(qlcheckr)
apply_checks(
  c(
    "You need to group by the State to summarise trips for each state." = !search_ast(ql_ast(), .expr = group_by(State)),
    "You need to use the summarise() function to sum trips for each state." = !search_ast(ql_ast(), .expr = summarise(Trips = sum(Trips)))
  )
)
```

::: { .hint exercise="summarise_tourism_by_state"}
::: { .callout-note collapse="false"}
## Hint

To summarise the number of trips by each State, start by grouping the data by State.

```r
tourism |>
  group_by(State)
```
:::
:::

::: { .hint exercise="summarise_tourism_by_state"}
::: { .callout-note collapse="false"}
## Hint

After grouping, use the `summarise()` function to sum the trips.

```r
tourism |>
  group_by(State) |>
  summarise(Trips = sum(Trips))
```
:::
:::
