---
title: "Week 10: Multiple regression and forecasting"
---

```{r}
week <- 10
source(here::here("course_info.R"))
```

## What you will learn this week

* Useful predictors for time series forecasting using regression
* Selecting predictors
* Ex ante and ex post forecasting

## Exercises (on your own or in tutorial)

Complete Exercises 9-13 from [Section 9.11 of the book](https://otexts.com/fpp3/arima-exercises.html).

## Exercise solutions

<!-- ::: {.callout appearance="minimal"} -->
<!-- <i class="bi bi-download"></i> [Week 10 Tutorial Solution.html](Week10.html){download="Week 10 Tutorial Solution.html"} -->
<!-- ::: -->


## Pre-seminar activities

Read [Chapter 7 of the textbook](https://otexts.com/fpp3/regression.html) and watch all embedded videos


<!-- ```{r} -->
<!-- #| output: asis -->
<!-- show_slides(week) -->
<!-- ``` -->

<!-- ## Seminar activities -->

<!-- ```{r} -->
<!-- #| child: activities.md -->
<!-- ``` -->


<!-- ## Seminar code -->

<!-- ::: {.callout appearance="minimal"} -->
<!-- <i class="bi bi-download"></i> [Seminar_code_week10.R](Seminar_code_week10.R){download="Seminar_code_week10.R"} -->
<!-- ::: -->



```{r, echo=FALSE}
#| output: asis
show_assignments(week)
```
