---
title: Group Assignments
---

It is expected that all group members participate equally to the group assignments. It sometimes helps to keep a log of the tasks each member is to complete. This may assist in keeping some balance throughout the semester. To ensure that all group members are contributing the following rules will apply for all the group assignments throughout the semester.

Every group member has the right to express concern/dislike in terms of a group member being absent from group activities. This has to be expressed directly to me (and only me) via a formal email stating facts that have hindered the operations of the group (saying I do not like George because he is tall is not a reason for expressing concern). If at least two such complaints are submitted during the completion of an assignment, the group member concerned will receive a warning. If the situation is not improved during the next assignment and another two complaints are again submitted, the group member will be immediately removed from the group and will be expected to complete the rest of the group assignments alone. 

In my involvement with group assignments we have rarely needed to enforce such rule so I do no expect any major problems here. However they will be enforced if need be. I hope this is clear. 

We need only **one submission per group** for each group assignment. 

## Group Assignment 1

The aim of this assignment is to meet your group members and begin interacting. Full marks will be allocated to the group by completing the tasks in the google form. Please try and be as efficient as possible in your writing (we are looking for short, sharp responses).

**Submission**

Fill in the [google form](https://forms.gle/f2EUGgPRcG8stYeG9) by **11.55 pm Wednesday 13th March 2024**.

