---
title: Group Assignment 2 (7%)
---

Use the "GA2_template.Rmd to get started. Leave the "## Questions" and the pagebreaks "\newpage" as they are (do not remove these - these will help with marking the assignment). You are to submit both an "GA2_GroupNo.Rmd" file and a compiled "GA2_GroupNo.pdf" file for your assignment.

Follow the assignment questions/instructions to complete some specific tasks. Add code were necessary (you can add more R chunks if and where you need to) and text to answer the questions where necessary. Keep within the suggested word restrictions in order to get full marks (marks will be deducted for grossly going over the word limit). This is to encourage you to be concise in your writing. 

You will be using this data in future assignments as you will build on the analysis you perform in this assignment. Furthermore, in the final assignment you will need to submit an .Rmd file that you will develop for all the assignment tasks throughout the semester. Marks will be allocated for code that runs without errors and produces the correct output. Make sure that every time your code works without errors. If you need help with this, please ask during consultation times. Keeping detailed comments in your program is always good practice (see for example the programs we are using in the lectures). This will help you remember in week 12 why you did certain things in week 4. 

**Files for download**:

<!-- * Download the template -->

<!-- ::: {.callout appearance="minimal"} -->
<!-- <i class="bi bi-download"></i> [Download template](../assignment_data/GA2_template.Rmd.zip){download="GA2_template.Rmd.zip"} -->
<!-- ::: -->

<!-- * Download the data  -->

<!-- ::: {.callout appearance="minimal"} -->
<!-- <i class="bi bi-download"></i> [Download GA_data.csv](../assignment_data/GA_data.csv){download="GA_data.csv"} -->
<!-- ::: -->


```{r}
#| output: asis
source(here::here("course_info.R"))
submit(schedule, "GA2")
```
