---
title: "Week 5: Exponential smoothing"
---

```{r}
week <- 5
source(here::here("course_info.R"))
```

## What you will learn this week

* Simple exponential smoothing
* Corresponding ETS models

## Exercises (on your own or in tutorial)

Complete Exercises 1-5, 8, 11-12 from [Section 5.11 of the book](https://otexts.com/fpp3/toolbox-exercises.html).

## Exercise solutions

<!-- ::: {.callout appearance="minimal"} -->
<!-- <i class="bi bi-download"></i> [Week 5 Tutorial Solution.html](Week5.html){download="Week 5 Tutorial Solution.html"} -->
<!-- ::: -->


## Pre-class activities

Read [Sections 8.1-8.4 of the textbook](https://otexts.com/fpp3/expsmooth.html) and watch all embedded videos


<!-- ```{r} -->
<!-- #| output: asis -->
<!-- show_slides(week) -->
<!-- ``` -->

<!-- ## Seminar activities -->

<!-- ```{r} -->
<!-- #| child: activities.md -->
<!-- ``` -->


<!-- ## Seminar code -->

<!-- ::: {.callout appearance="minimal"} -->
<!-- <i class="bi bi-download"></i> [Seminar_code_week5.R](Seminar_code_week5.R){download="Seminar_code_week5.R"} -->
<!-- ::: -->



```{r, echo=FALSE}
#| output: asis

show_assignments(week)
```
